#!/bin/bash

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_data_0625_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_2_train_img_only_ck_20_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_2/libero_wm_data_0625_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_20_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data/tokens_3/libero_wrist_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_2/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_4/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_5_256/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_256_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_only_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_512_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_abs_state_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_img_state_ck_1_512/record.json

# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_front_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512 --save_path /mnt/PLNAS/cenjun/processed_lerobot_data_rel_state_256_q0199/tokens/libero_wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll_his_1_train_a2i_512/record.json

python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_img_state_abs_ck_1_512 --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_img_state_abs_ck_1_512/record.json
# python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_img_state_rel_ck_1_512 --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_img_state_rel_ck_1_512/record.json

python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_rel_front_all_data --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_rel_front_all_data/record.json
python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_rel_wrist_all_data --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_rel_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_rel_wrist_all_data/record.json
python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_abs_front_all_data --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_abs_front_all_data/record.json
python -u concate_record.py --sub_record_dir /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_abs_wrist_all_data --save_path /mnt/PLNAS/cenjun/all_data/extracted/processed_lerobot_data_abs_state_256_minmax/tokens/libero_goal_his_1_train_a2i_512_abs_wrist_all_data/record.json




