# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/pc_03/grab_cup     --his 2     --len_action 20     --task_name data_0625_pc_03_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/pc_02/grab_cup     --his 2     --len_action 20     --task_name data_0625_pc_02_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/laptop_03/grab_cup     --his 2     --len_action 20     --task_name data_0625_laptop_03_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/pc_03/grab_strawberries     --his 2     --len_action 20     --task_name data_0623_pc_03_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/pc_02/grab_strawberries     --his 2     --len_action 20     --task_name data_0623_pc_02_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
# python action_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/laptop_03/grab_strawberries     --his 2     --len_action 20     --task_name data_0623_laptop_03_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs

python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/pc_03/grab_cup     --his 1    --task_name wm_data_0625_pc_03_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/pc_02/grab_cup     --his 1    --task_name wm_data_0625_pc_02_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0625/laptop_03/grab_cup     --his 1    --task_name wm_data_0625_laptop_03_grab_cup_so100_Pick-up-the-fallen-paper-cup-and-place-it-straight     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/pc_03/grab_strawberries     --his 1    --task_name wm_data_0623_pc_03_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/pc_02/grab_strawberries     --his 1    --task_name wm_data_0623_pc_02_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs
python world_model_conv_generation.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data/data_0623/laptop_03/grab_strawberries     --his 1    --task_name wm_data_0623_laptop_03_grab_strawberries_so100_Pick-up-the-strawberries-and-put-them-in-the-cup     --resolution 512     --output_dir /mnt/PLNAS/cenjun/lerobot_data/convs