# python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_03/grab_blocks     --his 1    --task_name data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_02/grab_blocks     --his 1    --task_name data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs

# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_03/grab_blocks     --his 1    --task_name wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_02/grab_blocks     --his 1    --task_name wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs

# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_03/grab_blocks     --his 1    --task_name wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/pc_02/grab_blocks     --his 1    --task_name wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs
# python world_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2/convs

python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_03/grab_blocks     --his 1    --task_name data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_02/grab_blocks     --his 1    --task_name data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python action_model_conv_generation_w_2.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs

python world_model_conv_generation_w_wrist.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_03/grab_blocks     --his 1    --task_name wm_wrist_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python world_model_conv_generation_w_wrist.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_02/grab_blocks     --his 1    --task_name wm_wrist_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python world_model_conv_generation_w_wrist.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name wm_wrist_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs

python world_model_conv_generation_w_front.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_03/grab_blocks     --his 1    --task_name wm_data_0623_pc_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python world_model_conv_generation_w_front.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/pc_02/grab_blocks     --his 1    --task_name wm_data_0623_pc_02_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs
python world_model_conv_generation_w_front.py     --base_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/data_0623/laptop_03/grab_blocks     --his 1    --task_name wm_data_0623_laptop_03_grab_blocks_so100_Pick-up-all-the-blocks-one-by-one-with-tweezers-and-put-them-in-the-roll     --resolution 512     --output_dir /mnt/PLNAS/cenjun/processed_lerobot_data_2_2/convs